# Generated by Django 4.0.5 on 2022-08-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boulangerie', '0004_remove_orderline_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderLine',
        ),
    ]
